import type { ParsedFile, TechDebtMetrics, ImpactChain } from '@/types/graph';
import { FILE_TYPE_CONFIG } from '@/types/graph';
import { computeImpact } from './impactAnalyzer';

export interface DocContext {
  file: ParsedFile;
  files: Map<string, ParsedFile>;
  metrics?: TechDebtMetrics;
  impact?: ImpactChain;
}

function getImpact(ctx: DocContext): ImpactChain {
  return ctx.impact ?? computeImpact(ctx.file.id, ctx.files);
}

function pad(n: number) { return String(n).padStart(3, '0'); }

// ─── Spec Doc ────────────────────────────────────────────────────────────────

export function generateSpecDoc(ctx: DocContext): string {
  const { file, files, metrics } = ctx;
  const impact = getImpact(ctx);
  const ext = files.get;
  const externalImports = file.imports.filter(i => !i.isRelative).map(i => i.raw);
  const localDeps = file.resolvedImports
    .map(id => files.get(id))
    .filter((f): f is ParsedFile => !!f);

  const lines: string[] = [
    `# Module Specification: \`${file.name}\``,
    '',
    `> Auto-generated by MFE Analyzer on ${new Date().toLocaleDateString()}`,
    '',
    '## Overview',
    '',
    `| Property | Value |`,
    `|----------|-------|`,
    `| **File** | \`${file.path}\` |`,
    `| **Type** | ${FILE_TYPE_CONFIG[file.type]?.label ?? file.type} |`,
    `| **Lines of Code** | ${file.linesOfCode} |`,
    `| **Exports** | ${file.exports.length} named symbols |`,
    metrics ? `| **Debt Score** | ${metrics.debtScore}/100 (${debtBand(metrics.debtScore)}) |` : '',
    '',
    '## Exported API',
    '',
    file.exports.length > 0
      ? file.exports.map(e => `- \`${e}\``).join('\n')
      : '_No exports detected_',
    '',
    '## Components',
    '',
    file.components.length > 0
      ? file.components.map(c => `- \`${c}\``).join('\n')
      : '_None_',
    '',
    '## Custom Hooks Used',
    '',
    file.hooks.length > 0
      ? file.hooks.map(h => `- \`${h}\``).join('\n')
      : '_None_',
    '',
    '## Routes Defined',
    '',
    file.routes.length > 0
      ? file.routes.map(r => `- \`${r}\``).join('\n')
      : '_No routes_',
    '',
    `## Local Dependencies (${localDeps.length})`,
    '',
    localDeps.length > 0
      ? localDeps.map(d => `- \`${d.name}\` — *${FILE_TYPE_CONFIG[d.type]?.label ?? d.type}*`).join('\n')
      : '_None_',
    '',
    `## External Packages (${externalImports.length})`,
    '',
    externalImports.length > 0
      ? externalImports.map(p => `- \`${p}\``).join('\n')
      : '_None_',
    '',
    '## Impact Summary',
    '',
    `- **Direct dependents:** ${impact.direct.length} files`,
    `- **Transitive dependents:** ${impact.transitive.length} files`,
    `- **Affected routes:** ${impact.affectedRoutes.length > 0 ? impact.affectedRoutes.join(', ') : 'none'}`,
    `- **Covered by test:** ${metrics ? (metrics.hasTest ? 'Yes' : 'No — ⚠️ no test file detected') : 'Unknown'}`,
  ];

  return lines.filter(l => l !== undefined).join('\n');
}

// ─── BRD ─────────────────────────────────────────────────────────────────────

export function generateBRD(ctx: DocContext): string {
  const { file, files, metrics } = ctx;
  const impact = getImpact(ctx);
  const directFiles = impact.direct.map(id => files.get(id)).filter((f): f is ParsedFile => !!f);
  const typeDesc: Record<string, string> = {
    page: 'This module represents a navigable page or screen within the application.',
    component: 'This module is a reusable UI component that can be embedded in multiple locations.',
    hook: 'This module encapsulates reusable stateful or side-effectful logic.',
    service: 'This module handles communication with external systems or APIs.',
    store: 'This module manages shared application state.',
    router: 'This module controls navigation and routing within the application.',
    config: 'This module provides configuration or constant values.',
    util: 'This module provides utility or helper functions.',
    test: 'This module contains automated tests.',
  };

  return [
    `# Business Requirements Document`,
    `## Module: \`${file.name}\``,
    '',
    `> Auto-generated by MFE Analyzer on ${new Date().toLocaleDateString()}`,
    '',
    '---',
    '',
    '## 1. Purpose',
    '',
    typeDesc[file.type] ?? 'General-purpose module.',
    '',
    `**Location:** \`${file.path}\``,
    '',
    '## 2. Functional Scope',
    '',
    '### Capabilities Exposed',
    '',
    file.exports.length > 0
      ? file.exports.map(e => `- \`${e}\``).join('\n')
      : '_No exported capabilities detected_',
    '',
    file.routes.length > 0 ? ['### Routes', '', ...file.routes.map(r => `- \`${r}\``)].join('\n') : '',
    '',
    '### Navigation Flows',
    '',
    file.navLinks.length > 0
      ? file.navLinks.map(l => `- Navigates to \`${l.target}\` via ${l.type === 'link' ? '`<Link>`' : '`navigate()`'}`).join('\n')
      : '_No navigation links detected_',
    '',
    '## 3. Integration Points',
    '',
    `### Consumed By (${directFiles.length} direct consumers)`,
    '',
    directFiles.length > 0
      ? directFiles.map(f => `- \`${f.name}\` (${FILE_TYPE_CONFIG[f.type]?.label ?? f.type})`).join('\n')
      : '_Not consumed by any other module_',
    '',
    '## 4. Technical Constraints',
    '',
    `| Metric | Value | Status |`,
    `|--------|-------|--------|`,
    `| Lines of Code | ${file.linesOfCode} | ${file.linesOfCode > 500 ? '⚠️ Large file' : '✅'} |`,
    metrics ? `| Fan-in (dependents) | ${metrics.fanIn} | ${metrics.fanIn > 10 ? '⚠️ High coupling' : '✅'} |` : '',
    metrics ? `| Fan-out (dependencies) | ${metrics.fanOut} | ${metrics.fanOut > 10 ? '⚠️ High coupling' : '✅'} |` : '',
    metrics?.circularWith?.length ? `| Circular Dependencies | Yes — with ${metrics.circularWith.length} module(s) | ⚠️ Risk |` : '| Circular Dependencies | None detected | ✅ |',
    metrics ? `| Test Coverage | ${metrics.hasTest ? 'Test file detected' : 'No test file'} | ${metrics.hasTest ? '✅' : '⚠️'} |` : '',
    '',
    '## 5. Open Questions',
    '',
    `- [ ] Are all ${file.exports.length} exported symbols intentionally public?`,
    `- [ ] ${metrics?.hasTest ? 'Test file exists — verify test coverage is adequate.' : '**No test file detected** — should this module be tested?'}`,
    metrics?.circularWith?.length ? `- [ ] Circular dependency detected — review import relationships with: ${metrics.circularWith.slice(0, 3).join(', ')}` : '',
    `- [ ] Has this module's behaviour been validated for all consuming modules (${impact.totalImpact} total)?`,
  ].filter(l => l !== undefined && l !== '').join('\n');
}

// ─── SIT Cases ───────────────────────────────────────────────────────────────

export function generateSITCases(ctx: DocContext): string {
  const { file, files, metrics } = ctx;
  const externalImports = file.imports.filter(i => !i.isRelative).map(i => i.raw);
  const localDeps = file.resolvedImports
    .map(id => files.get(id))
    .filter((f): f is ParsedFile => !!f);

  const cases: string[] = [
    `# System Integration Test Cases`,
    `## Module: \`${file.name}\` (${FILE_TYPE_CONFIG[file.type]?.label ?? file.type})`,
    '',
    `> Auto-generated by MFE Analyzer on ${new Date().toLocaleDateString()}`,
    '',
    '---',
    '',
    '## Pre-conditions',
    '',
    `- Application is fully built and deployed to test environment`,
    `- All ${localDeps.length} local dependencies are available and functioning`,
    externalImports.length > 0 ? `- External packages available: ${externalImports.map(p => `\`${p}\``).join(', ')}` : '',
    '',
    '---',
    '',
    `### TC-${file.name.toUpperCase()}-${pad(1)}: Module loads without errors`,
    '',
    `**Given** the application is running  `,
    `**When** the module \`${file.name}\` is initialised  `,
    `**Then** no console errors or unhandled exceptions are thrown  `,
    `**And** all ${localDeps.length} local dependencies resolve correctly`,
    '',
  ];

  let n = 2;
  for (const comp of file.components.slice(0, 5)) {
    cases.push(
      `### TC-${file.name.toUpperCase()}-${pad(n++)}: \`${comp}\` renders correctly`,
      '',
      `**Given** the application is in a valid state  `,
      `**When** \`${comp}\` is rendered  `,
      `**Then** the component mounts without errors  `,
      `**And** expected UI elements are present in the DOM`,
      '',
    );
  }

  for (const route of file.routes.slice(0, 5)) {
    cases.push(
      `### TC-${file.name.toUpperCase()}-${pad(n++)}: Route \`${route}\` resolves`,
      '',
      `**Given** the user is authenticated (if required)  `,
      `**When** the application navigates to \`${route}\`  `,
      `**Then** the page loads without errors  `,
      `**And** the expected view is displayed within 3 seconds`,
      '',
    );
  }

  if (metrics?.circularWith?.length) {
    cases.push(
      `### TC-${file.name.toUpperCase()}-${pad(n++)}: Circular dependency does not cause runtime failure`,
      '',
      `**Given** all modules in the circular group are loaded  `,
      `**When** module initialisation order is exercised  `,
      `**Then** no initialisation errors occur  `,
      `**And** all exports are accessible`,
      '',
    );
  }

  cases.push(
    `### TC-${file.name.toUpperCase()}-${pad(n++)}: Import chain integrity`,
    '',
    `**Given** the module and its ${localDeps.length} local dependencies are deployed  `,
    `**When** all imports are resolved at runtime  `,
    `**Then** no missing module errors are thrown  `,
    `**And** all exported symbols are accessible from consuming modules`,
    '',
  );

  return cases.filter(l => l !== undefined).join('\n');
}

// ─── UAT Cases ───────────────────────────────────────────────────────────────

export function generateUATCases(ctx: DocContext): string {
  const { file } = ctx;
  const impact = getImpact(ctx);

  const cases: string[] = [
    `# User Acceptance Test Cases`,
    `## Feature: \`${file.name}\` (${FILE_TYPE_CONFIG[file.type]?.label ?? file.type})`,
    '',
    `> Auto-generated by MFE Analyzer on ${new Date().toLocaleDateString()}`,
    '',
    '---',
    '',
    '## Personas',
    '- **End User** — standard application user',
    '- **Admin** — privileged user (if routes are protected)',
    '',
    '---',
    '',
  ];

  let n = 1;

  for (const route of file.routes.slice(0, 5)) {
    cases.push(
      `### UAT-${file.name.toUpperCase()}-${pad(n++)}: Page \`${route}\` is accessible`,
      '',
      `**As a** user  `,
      `**When I** navigate to \`${route}\`  `,
      `**Then I** should see the page load within 3 seconds  `,
      `**And** the content matches the expected layout  `,
      `**And** no error messages are displayed`,
      '',
    );
  }

  for (const link of file.navLinks.slice(0, 5)) {
    cases.push(
      `### UAT-${file.name.toUpperCase()}-${pad(n++)}: Navigation to \`${link.target}\` works`,
      '',
      `**As a** user  `,
      `**When I** click the ${link.type === 'link' ? 'navigation link' : 'button/action'} pointing to \`${link.target}\`  `,
      `**Then I** should be taken to \`${link.target}\` without errors  `,
      `**And** the back/forward browser history should work correctly`,
      '',
    );
  }

  for (const comp of file.components.slice(0, 3)) {
    cases.push(
      `### UAT-${file.name.toUpperCase()}-${pad(n++)}: \`${comp}\` is interactive`,
      '',
      `**As a** user  `,
      `**When I** interact with \`${comp}\`  `,
      `**Then I** should receive appropriate visual feedback  `,
      `**And** no unexpected errors should occur`,
      '',
    );
  }

  cases.push(
    `### UAT-${file.name.toUpperCase()}-${pad(n++)}: No performance degradation`,
    '',
    `**As a** user  `,
    `**When I** use features provided by \`${file.name}\`  `,
    `**Then I** should not experience noticeable lag or layout shifts  `,
    `**And** time to interactive should remain acceptable`,
    '',
    '## Acceptance Criteria',
    '',
    `- [ ] All UAT scenarios pass without defects`,
    `- [ ] \`${file.name}\` behaves identically across Chrome, Firefox, and Safari`,
    `- [ ] No regressions in the ${impact.direct.length} directly dependent modules`,
    `- [ ] Accessibility (WCAG 2.1 AA) requirements are met`,
  );

  return cases.filter(l => l !== undefined).join('\n');
}

// ─── Utilities ───────────────────────────────────────────────────────────────

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function debtBand(score: number): string {
  if (score <= 20) return 'Clean';
  if (score <= 40) return 'Low';
  if (score <= 60) return 'Medium';
  if (score <= 80) return 'High';
  return 'Critical';
}
