/**
 * PlantUML diagram generation from static analysis data.
 * Four diagram types:
 *  - fileDiagram   : one file — component, props, imports
 *  - moduleDiagram : whole project — files as classes, import arrows, grouped by folder
 *  - journeyDiagram: whole project — routes as states, nav links as transitions
 *  - classDiagram  : whole project — TypeScript interfaces + components that use them
 */

import type { ParsedFile } from '@/types/graph';
import { FILE_TYPE_CONFIG } from '@/types/graph';

// ─── Utilities ────────────────────────────────────────────────────────────────

/** Make a safe PlantUML identifier from any string */
function id(s: string): string {
  return s.replace(/[^A-Za-z0-9]/g, '_').replace(/^_+/, '') || '_root';
}

/** Strip # from colour for class-level annotations */
function col(hex: string): string {
  return hex.replace('#', '');
}

function typeBg(type: string): string {
  return col(FILE_TYPE_CONFIG[type as keyof typeof FILE_TYPE_CONFIG]?.bg ?? '#1E293B');
}

function typeLabel(type: string): string {
  return FILE_TYPE_CONFIG[type as keyof typeof FILE_TYPE_CONFIG]?.label ?? type;
}

/** Shared dark theme skinparam block */
const THEME = `
skinparam backgroundColor #0F172A
skinparam defaultFontName monospace
skinparam classBorderColor #334155
skinparam classBackgroundColor #1E293B
skinparam classFontColor #F1F5F9
skinparam classHeaderBackgroundColor #1E293B
skinparam classAttributeIconSize 0
skinparam arrowColor #475569
skinparam arrowFontColor #94A3B8
skinparam arrowFontSize 9
skinparam packageBackgroundColor #0F172A
skinparam packageBorderColor #1E293B
skinparam packageFontColor #94A3B8
skinparam noteFontSize 9
skinparam noteBackgroundColor #1E293B
skinparam noteBorderColor #334155
skinparam noteFontColor #94A3B8
skinparam stereotypeFontColor #64748B
`.trim();

const HEADER_COMMENT = `' Generated by React Analyzer — https://github.com/kkiran33/react-analyzer
' View online: paste at https://www.plantuml.com/plantuml/
' VS Code: install "PlantUML" extension by jebbs`;

// ─── 1. File diagram ─────────────────────────────────────────────────────────

export function generateFileDiagram(file: ParsedFile, allFiles: Map<string, ParsedFile>): string {
  const out: string[] = [
    `@startuml ${id(file.name)}`,
    HEADER_COMMENT,
    '',
    `title ${file.name}  [${typeLabel(file.type)}]`,
    '',
    THEME,
    '',
  ];

  const fileId = id(file.name);
  const bg = typeBg(file.type);
  const stereotype = `<<${typeLabel(file.type)}>>`;

  // Main node
  out.push(`class "${file.name}" as ${fileId} ${stereotype} #${bg} {`);

  // Component props
  if (file.componentInfo.length > 0) {
    for (const ci of file.componentInfo) {
      if (ci.props.length > 0) {
        out.push(`  .. ${ci.name} props ..`);
        for (const p of ci.props.slice(0, 10)) {
          out.push(`  ${p.required ? '+' : '-'} ${p.name} : ${p.type}`);
        }
        if (ci.props.length > 10) out.push(`  .. +${ci.props.length - 10} more ..`);
      }
    }
  }

  // Exports
  if (file.exports.length > 0) {
    out.push('  .. exports ..');
    for (const e of file.exports.slice(0, 8)) {
      out.push(`  + ${e}`);
    }
    if (file.exports.length > 8) out.push(`  .. +${file.exports.length - 8} more ..`);
  }

  // Hooks used
  if (file.hooks.length > 0) {
    out.push('  .. hooks ..');
    for (const h of file.hooks.slice(0, 6)) out.push(`  ~ ${h}()`);
    if (file.hooks.length > 6) out.push(`  .. +${file.hooks.length - 6} more ..`);
  }

  // Routes
  if (file.routes.length > 0) {
    out.push('  .. routes ..');
    for (const r of file.routes) out.push(`  {${r}}`);
  }

  out.push('}');
  out.push('');

  // Internal deps package
  const internalDeps = file.resolvedImports
    .map(i => allFiles.get(i))
    .filter((f): f is ParsedFile => !!f);

  if (internalDeps.length > 0) {
    out.push('package "Internal Imports" #0A1020 {');
    for (const dep of internalDeps.slice(0, 12)) {
      out.push(`  class "${dep.name}" as ${id(dep.path)} <<${typeLabel(dep.type)}>> #${typeBg(dep.type)}`);
    }
    out.push('}');
    out.push('');
    for (const dep of internalDeps.slice(0, 12)) {
      out.push(`${fileId} --> ${id(dep.path)} : uses`);
    }
    out.push('');
  }

  // External packages
  const exts = file.imports
    .filter(i => !i.isRelative)
    .map(i => ({ raw: i.raw, names: i.names }))
    .filter((v, i, a) => a.findIndex(x => x.raw === v.raw) === i)
    .slice(0, 8);

  if (exts.length > 0) {
    out.push('package "External Packages" #0A1020 {');
    for (const pkg of exts) {
      const display = pkg.raw.length > 30 ? pkg.raw.slice(0, 27) + '...' : pkg.raw;
      out.push(`  class "${display}" as ${id(pkg.raw)} <<npm>> #1C1917`);
    }
    out.push('}');
    out.push('');
    for (const pkg of exts) {
      const names = pkg.names.length > 0 ? ` : {${pkg.names.slice(0, 4).join(', ')}}` : '';
      out.push(`${fileId} ..> ${id(pkg.raw)}${names}`);
    }
    out.push('');
  }

  // Metadata note
  out.push(`note bottom of ${fileId}`);
  out.push(`  Path: ${file.path}`);
  out.push(`  Lines of code: ${file.linesOfCode}`);
  if (file.astParsed) out.push('  AST parsed: full accuracy');
  out.push('end note');

  out.push('');
  out.push('@enduml');

  return out.join('\n');
}

// ─── 2. Module dependency diagram ────────────────────────────────────────────

export function generateModuleDiagram(files: Map<string, ParsedFile>): string {
  const MAX_FILES = 80;

  // Score files by connectivity — show most connected first
  const scored = [...files.values()]
    .filter(f => f.type !== 'test')
    .map(f => ({
      file: f,
      score: f.resolvedImports.length + [...files.values()].filter(o => o.resolvedImports.includes(f.id)).length,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, MAX_FILES)
    .map(x => x.file);

  const shown = new Set(scored.map(f => f.id));

  // Group by top-level directory
  const groups = new Map<string, ParsedFile[]>();
  for (const file of scored) {
    const topDir = file.dir.split('/')[0] ?? 'root';
    if (!groups.has(topDir)) groups.set(topDir, []);
    groups.get(topDir)!.push(file);
  }

  const out: string[] = [
    '@startuml ModuleMap',
    HEADER_COMMENT,
    '',
    `title Module Dependency Map  (${scored.length} files${files.size > MAX_FILES ? `, top ${MAX_FILES} by connectivity` : ''})`,
    '',
    'left to right direction',
    '',
    THEME,
    '',
  ];

  for (const [dir, group] of groups) {
    out.push(`package "${dir}" {`);
    for (const f of group) {
      const bg = typeBg(f.type);
      const stereo = `<<${typeLabel(f.type)}>>`;
      out.push(`  class "${f.name}" as ${id(f.id)} ${stereo} #${bg}`);
    }
    out.push('}');
    out.push('');
  }

  // Edges
  const edgeSet = new Set<string>();
  for (const f of scored) {
    for (const depId of f.resolvedImports) {
      if (!shown.has(depId)) continue;
      const e = `${id(f.id)} --> ${id(depId)}`;
      if (!edgeSet.has(e)) { edgeSet.add(e); out.push(e); }
    }
  }

  out.push('');
  out.push('@enduml');
  return out.join('\n');
}

// ─── 3. Page journey diagram ─────────────────────────────────────────────────

export function generateJourneyDiagram(files: Map<string, ParsedFile>): string {
  const out: string[] = [
    '@startuml JourneyMap',
    HEADER_COMMENT,
    '',
    'title Page Navigation Journey',
    '',
    THEME,
    'skinparam stateBorderColor #3B82F6',
    'skinparam stateBackgroundColor #1E3A5F',
    'skinparam stateFontColor #93C5FD',
    'skinparam stateArrowColor #3B82F6',
    '',
  ];

  // Collect unique routes
  const routes = [...new Set([...files.values()].flatMap(f => f.routes))];

  if (routes.length === 0) {
    out.push('note "No routes detected in this codebase."');
    out.push('@enduml');
    return out.join('\n');
  }

  // Collision-free, stable state id per route
  const stateIds = new Map<string, string>();
  const usedIds = new Set<string>();
  for (const route of routes) {
    let base = 'r_' + route.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
    if (base === 'r_') base = 'r_root';
    if (route.includes('*')) base = 'r_wildcard';
    let candidate = base, n = 2;
    while (usedIds.has(candidate)) candidate = `${base}_${n++}`;
    usedIds.add(candidate);
    stateIds.set(route, candidate);
  }
  const sid = (route: string) => stateIds.get(route) ?? 'r_unknown';

  // Map each route to the page file that renders it (by naming convention)
  const ownerFile = new Map<string, ParsedFile>();
  for (const route of routes) {
    const file = matchRouteToFile(route, files);
    if (file) ownerFile.set(route, file);
  }

  // Emit states
  out.push('[*] --> entry : app start');
  out.push('');
  for (const route of routes) {
    const file = ownerFile.get(route);
    const component = file?.componentInfo[0]?.name ?? file?.components[0] ?? file?.name ?? 'route';
    const guarded = isRouteGuarded(route, file, files);
    const protTag = guarded ? '  <<auth>>' : '';
    out.push(`state "${route || '/'}${protTag}" as ${sid(route)} {`);
    out.push(`  ${component}`);
    out.push('}');
  }
  out.push('');

  // Entry → root route (/ or shortest)
  const rootRoute = routes.includes('/') ? '/' : [...routes].sort((a, b) => a.length - b.length)[0];
  if (rootRoute) out.push(`entry --> ${sid(rootRoute)} : initial load`);
  out.push('');

  // Navigation transitions: from a route, follow its page's import subtree,
  // collect navLinks, map each target back to a route.
  const transSet = new Set<string>();
  for (const route of routes) {
    const file = ownerFile.get(route);
    if (!file) continue;
    const subtree = collectSubtree(file, files, 3);
    for (const member of subtree) {
      for (const link of member.navLinks) {
        const target = matchTargetRoute(link.target, routes);
        if (!target || target === route) continue;
        const key = `${sid(route)}->${sid(target)}->${link.type}`;
        if (transSet.has(key)) continue;
        transSet.add(key);
        const label = link.type === 'navigate' ? 'navigate()' : '<Link>';
        out.push(`${sid(route)} --> ${sid(target)} : ${label}`);
      }
    }
  }
  out.push('');

  // Route nesting (parent → child) as dashed
  const nestSet = new Set<string>();
  for (const route of routes) {
    const segments = route.split('/').filter(Boolean);
    if (segments.length < 2) continue;
    const parent = '/' + segments.slice(0, -1).join('/');
    if (!routes.includes(parent)) continue;
    const key = `${sid(parent)}..>${sid(route)}`;
    if (nestSet.has(key)) continue;
    nestSet.add(key);
    out.push(`${sid(parent)} ..> ${sid(route)} : nested`);
  }

  out.push('');
  out.push('@enduml');
  return out.join('\n');
}

/** Match a route path to the page file that renders it, by naming convention. */
function matchRouteToFile(route: string, files: Map<string, ParsedFile>): ParsedFile | undefined {
  const segs = route.split('/').filter(Boolean);
  const last = segs[segs.length - 1] ?? '';
  // /fire-progress -> fireprogress
  const slug = last.replace(/[^A-Za-z0-9]/g, '').toLowerCase();

  const candidates = [...files.values()].filter(f => f.type !== 'test');
  const norm = (s: string) => s.replace(/[^A-Za-z0-9]/g, '').toLowerCase();

  // Root route → Landing/Home/Index/App
  if (segs.length === 0 || route === '/') {
    const rootNames = ['landing', 'home', 'index', 'app', 'root', 'dashboard'];
    for (const rn of rootNames) {
      const hit = candidates.find(f => f.type === 'page' && norm(f.name).includes(rn))
        ?? candidates.find(f => norm(f.name) === rn);
      if (hit) return hit;
    }
    return undefined;
  }

  // Exact-ish: page file whose normalized name contains the slug
  const pages = candidates.filter(f => f.type === 'page');
  return pages.find(f => norm(f.name) === slug || norm(f.name) === slug + 'page')
    ?? pages.find(f => norm(f.name).includes(slug) && slug.length > 2)
    ?? candidates.find(f => norm(f.name).includes(slug) && slug.length > 2);
}

/** BFS over resolvedImports from a root file, up to depth. */
function collectSubtree(root: ParsedFile, files: Map<string, ParsedFile>, depth: number): ParsedFile[] {
  const seen = new Set<string>([root.id]);
  const result: ParsedFile[] = [root];
  let frontier = [root];
  for (let d = 0; d < depth; d++) {
    const next: ParsedFile[] = [];
    for (const f of frontier) {
      for (const dep of f.resolvedImports) {
        if (seen.has(dep)) continue;
        const df = files.get(dep);
        if (!df) continue;
        seen.add(dep);
        result.push(df);
        next.push(df);
      }
    }
    frontier = next;
  }
  return result;
}

/** Resolve a navLink target to a known route (exact, dynamic, or prefix). */
function matchTargetRoute(target: string, routes: string[]): string | null {
  if (routes.includes(target)) return target;
  for (const r of routes) {
    const rp = r.split('/'), tp = target.split('/');
    if (rp.length === tp.length && rp.every((p, i) => p.startsWith(':') || p === tp[i])) return r;
  }
  const parts = target.split('/').filter(Boolean);
  for (let i = parts.length; i > 0; i--) {
    const candidate = '/' + parts.slice(0, i).join('/');
    if (routes.includes(candidate)) return candidate;
  }
  return null;
}

/** A route is guarded only if its own page subtree imports a guard component. */
function isRouteGuarded(route: string, file: ParsedFile | undefined, files: Map<string, ParsedFile>): boolean {
  if (!file) return false;
  const guard = /PrivateRoute|RequireAuth|ProtectedRoute|AuthGuard|withAuth/;
  return collectSubtree(file, files, 2).some(f => f.imports.some(i => guard.test(i.raw)));
}

// ─── 4. TypeScript class / interface diagram ──────────────────────────────────

export function generateClassDiagram(files: Map<string, ParsedFile>): string {
  const out: string[] = [
    '@startuml ClassMap',
    HEADER_COMMENT,
    '',
    'title TypeScript Interface & Component Map',
    '',
    THEME,
    'skinparam interfaceBorderColor #8B5CF6',
    'skinparam interfaceBackgroundColor #2E1065',
    'skinparam interfaceFontColor #C4B5FD',
    '',
  ];

  // Collect all unique interfaces across all files
  const ifaceMap = new Map<string, { props: { name: string; type: string; required: boolean }[] }>();
  for (const file of files.values()) {
    for (const iface of file.interfaceDefinitions) {
      if (!ifaceMap.has(iface.name) && iface.props.length > 0) {
        ifaceMap.set(iface.name, { props: iface.props });
      }
    }
  }

  if (ifaceMap.size === 0) {
    out.push('note "No TypeScript interfaces found.\\nThis codebase may use inline prop types."');
    out.push('@enduml');
    return out.join('\n');
  }

  // Emit interfaces
  for (const [name, iface] of ifaceMap) {
    out.push(`interface "${name}" {`);
    for (const p of iface.props.slice(0, 12)) {
      out.push(`  ${p.required ? '+' : '-'} ${p.name} : ${p.type}`);
    }
    if (iface.props.length > 12) out.push(`  .. +${iface.props.length - 12} more ..`);
    out.push('}');
    out.push('');
  }

  // Link components that reference each interface
  const emittedComps = new Set<string>();
  for (const file of files.values()) {
    for (const ci of file.componentInfo) {
      if (!ci.propsTypeName || !ifaceMap.has(ci.propsTypeName)) continue;
      if (!emittedComps.has(ci.name)) {
        emittedComps.add(ci.name);
        const bg = typeBg('component');
        out.push(`class "${ci.name}" <<Component>> #${bg}`);
      }
      out.push(`"${ci.name}" ..|> "${ci.propsTypeName}" : props`);
    }
  }

  // Show any interface-to-interface relationships (type references)
  for (const [name, iface] of ifaceMap) {
    for (const prop of iface.props) {
      const refType = prop.type.replace('[]', '').split('<')[0];
      if (ifaceMap.has(refType)) {
        out.push(`"${name}" --> "${refType}" : ${prop.name}`);
      }
    }
  }

  out.push('');
  out.push('@enduml');
  return out.join('\n');
}

// ─── Download utility ────────────────────────────────────────────────────────

export function downloadPlantUml(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
